### PR TITLE
feat: add scrollbar to the menu when the symbol list is too long

### PR DESCRIPTION
**Pull request by willothy**
Saw this on the todo list, thought it would be nice to have.

### CODE REVIEW

**Comment by willothy** [comment]
This is compatible with the fuzzy finding feature, I have a patch ready in another branch for when both are merged :)

**Comment by Bekaboo** [comment]
@willothy This is amazing, ty!

**Comment by willothy** [comment]
> @willothy This is amazing, ty!

Totally, glad to contribute! I've been enjoying working in this codebase and have found this plugin extremely useful :)

**Comment by Bekaboo** [comment]
@willothy `scrolloff` is set to 0 deliberately to avoid the menu being shifted on mouse click when the clicked symbol is within the range of `scrolloff` to the upper/lower border of the window:

scrolloff-shift

**Comment by willothy** [comment]
Ah, that makes sense! I'll remove that from this branch.

**Pull request merged**
