### PR TITLE
feat: use dropbar menu for `ui.select` (opt-in)

### PR DESCRIPTION
**Pull request by willothy**

### CODE REVIEW

**Comment by Bekaboo** [comment]
Awesome work. IMO better to just provide the function and let users override `ui.select` themselves. Need to provide some guidance/instructions in the README.

**Comment by willothy** [comment]
> Awesome work. IMO better to just provide the function and let users override `ui.select` themselves. Need to provide some guidance/instructions in the README.

Thanks! Sounds good, I like that approach more now that I think about it.

**Comment by Bekaboo** [comment]
Should also update vim help file. If you do not have time I can do it. I have to admit it is pretty cumbersome to write all these docs manually. Have to find a way to generate them automatically.

**Comment by willothy** [comment]
Will do! My bad, I always forget about vimdoc. Definitely would be good to setup panvimdoc or something, but from my experience it can be tricky to get working with a readme that isn't designed from scratch to work with panvimdoc

**Comment by willothy** [comment]
Ok docs should be good, hope the formatting is ok

**Comment by Bekaboo** [comment]
Looks great, thanks!

**Pull request merged**
