### PR TITLE
feat(fzf): allow fzf win_configs to contain functions, fix vertical offsets

### PR DESCRIPTION
**Pull request by willothy**
This PR fixes the issue with fzf placement I mentioned in #123.

### CODE REVIEW

**Comment by Bekaboo** [comment]
Thanks! It is not clear to me what is the exact bug and how to reproduce it.

**Comment by willothy** [comment]
> Thanks! It is not clear to me what is the exact bug and how to reproduce it.
> 
> EDIT: In addition could you explain how it works and what problem it addresses? I tried to understand but the logic seems a bit twisted.

Essentially, the fzf menu uses relative=win, so with anchor the position can be off by a few cells depending on the border and can end up overlapping the menu (covering entries).

This fixes the vertical overlap and ensures the fzf menu is always just a small bar at the bottom.

> EDIT 2: Also observed that the offset of fzf window is wrong when border is 'single' (not introduced by this PR):
> 
> image
> 
> Could we fix it in this PR too?

Sure! That's exactly the issue I was trying to fix (some other cases of it as well). It was overlapping vertically on some occasions, that's what I've fixed so far. I'll look into the horizontal position now.

**Comment by willothy** [comment]
I'll try to provide a video or something later but honestly this one is hard to explain lol.

It happens with certain scroll positions, when the menu opens *above* the cursor only.

**Comment by Bekaboo** [comment]
@willothy The misalignment should be fixed now, can you confirm?

**Comment by willothy** [comment]
> @willothy The misalignment should be fixed now, can you confirm?

Partially, but there are still the header cases to handle. I'll update this PR.

**Comment by willothy** [comment]
It affects vertical alignment. There can be a gap above the fzf window, or an empty row if there's a header (like in the ui-select menu, which uses only a top border).

**Comment by Bekaboo** [comment]
@willothy Do you mean the header of the fzf window?

**Comment by willothy** [comment]
Yeah, it can inherit a header from the parent window. I will update this PR to only fix that and remove the things you fixed.

**Comment by willothy** [comment]
Should be good now

**Comment by Bekaboo** [comment]
@willothy I cannot reproduce the bug where the menu is overlapped with the title/header of the fzf window using the script below, with `vim.ui.select()` being replaced by dropbar's select menu:

```lua
vim.ui.select({ "tabs", "spaces" }, {
	prompt = "Select tabs or spaces:",
	format_item = function(item)
		return "I'd like to choose " .. item
	end,
}, function() end)

```

However, I can observe that the fzf window has an improperly thick top  border because it inherits the border from the select menu (`border = { "", " ", "", "", "", "", "", "" }`:

image

Can we just merge `opts.win_configs` and fzf-window-specific window configs in `fuzzy_find_open()`, excluding `self._win_configs`? That should be a simpler solution. Notice that we have to re-evaluate the merged result using `eval_win_configs()`.

**Comment by willothy** [comment]
> @willothy I cannot reproduce the bug where the menu is overlapped with the title/header of the fzf window using the script below, with `vim.ui.select()` being replaced by dropbar's select menu:

It can occur both ways, either with overlap or the thick border, depending on factors I have not yet determined. I will see if your new commits have fixed it on my end.

**Comment by willothy** [comment]
Ok I now don't have the overlap issue, but I do have the thick border issue.

**Comment by willothy** [comment]
> Can we just merge `opts.win_configs` and fzf-window-specific window configs in `fuzzy_find_open()`, excluding `self._win_configs`? That should be a simpler solution. Notice that we have to re-evaluate the merged result using `eval_win_configs()`.

I don't think so, because then it would break some configs that use borders. I think the complex checks are kinda needed here tbh. Not 100% sure though, I'm testing the idea right now. Have just not found a solution that works for all edge cases.

**Comment by Bekaboo** [comment]
> I don't think so, because then it would break some configs that use borders

Why does it break configs for borders given that `opts.win_configs` contains options for borders?

**Comment by willothy** [comment]
> > I don't think so, because then it would break some configs that use borders
> 
> Why does it break configs for borders given that `opts.win_configs` contains options for borders?

Because those can be fzf-specific I think. Honestly I'm not sure. But without self._win_configs.border the border doesn't inherit properly. I am looking into it to provide a more specific repro, sorry for not explaining well lol

**Comment by Bekaboo** [comment]
Emm I think the border of the menu is calculated from `opts.menu.win_configs` right? So it may be sufficient to use the option value to determine the fzf window's border.

**Comment by willothy** [comment]
Sounds good, I will keep trying different configurations of this.

**Comment by willothy** [comment]
I am struggling to implement something that works with all three of (1) full borders provided by name, (2) full borders provided by array and (3) partial borders provided by array.

I can get either partial borders or full borders to work but not both lol

**Comment by Bekaboo** [comment]
@willothy You can leave it to me if you find it hard to implement. I will give it a closer look later.

**Comment by willothy** [comment]
I think I'll be able to do it (feel free to have a look though),I am just not sure how the fzf window can inherit the parent window's border without having the thick header, unless we manually remove the header or add a hack *just* for the ui-select implementation which I don't think is ideal.

**Comment by willothy** [comment]
This seems to work well, it is a mix of your idea and removing the top border when possible.

**Comment by willothy** [comment]
Actually, maybe we should leave the border alone since the border for the fzf window is already configurable separately from the menu, so if the users would like to get rid of the thicker header they can. We can also update the defaults so that the fzf menu does not have a thick header by default. Thoughts?

**Comment by Bekaboo** [comment]
@willothy Sorry my fault, I thought that `opts.win_configs` is `opts.menu.win_configs` but turns out it is `opts.fzf.win_configs`. Why is this config file empty by default? It should be like `opts.menu.win_config`, having all necessary fields. We should do all the calculations there.

**Comment by willothy** [comment]
No worries!

I think it is nice to have them dynamic though, so maybe nice to keep updating in the function - I have an idea that involves changing the border at runtime, I will take a video of it and push the required change.

**Comment by Bekaboo** [comment]
> I have an idea that involves changing the border at runtime

What is the use case for this?

**Comment by willothy** [comment]
It's kinda useless so no worries if you don't want to add it, but it looks super nice. Here:

https://github.com/Bekaboo/dropbar.nvim/assets/38540736/c0fcd991-edf0-4829-a68c-05702b1677f6

**Comment by willothy** [comment]
Moved as much config as could be moved into the defaults.

**Comment by Bekaboo** [comment]
> It's kinda useless so no worries if you don't want to add it, but it looks super nice. Here:
> 2024-01-24.20-13-16.mp4

This looks cool and is achievable if we allow `win_configs` to be a function. One can change the border of the menu window using `nvim_open_win()` and register a autocmd to restore the original border on `WinClosed`

**Comment by willothy** [comment]
The change in this PR now allows win_configs to be a function (it already did since we're using opts.win_configs now), and also recomputes a menu's border when the fzf window is opened/closed.

**Comment by Bekaboo** [comment]
No, I mean allowing `win_configs` itself to be a function, not a table containing functions. It will be more convenient when you want to change a bunch of window config fields in different situations.

**Comment by Bekaboo** [comment]
I will see if I can move more window configs to the opts table and eliminate the top border later.

**Comment by willothy** [comment]
> No, I mean allowing `win_configs` itself to be a function, not a table containing functions. It will be more convenient when you want to change a bunch of window config fields in different situations.

Ohhh interesting! I like that idea.

**Comment by willothy** [comment]
> I will see if I can move more window configs to the opts table and eliminate the top border later.

I actually don't think we should change the border manually as it could introduce unexpected behavior. I have a different idea: I think we should allow each menu to have a `win_configs` field for its fzf window, so that fzf windows can be configured per-menu as well as globally. That solves the ui-select issue without doing anything hacky that only affects that part of the plugin.

**Comment by Bekaboo** [comment]
> > I will see if I can move more window configs to the opts table and eliminate the top border later.
> 
> I actually don't think we should change the border manually as it could introduce unexpected behavior. I have a different idea: I think we should allow each menu to have a `win_configs` field for its fzf window, so that fzf windows can be configured per-menu as well as globally. That solves the ui-select issue without doing anything hacky that only affects that part of the plugin.

Sounds good!

**Comment by Bekaboo** [comment]
> win_configs as function should be working, fzf options is WIP.

Thanks! I will be a bit busy in the following two or three days, I will be back and pick these changes as soon as possible and sorry for the latency in advance.

**Comment by willothy** [comment]
No worries at all! No need to apologize.

**Comment by willothy** [comment]
Hmm actually after thinking about it I don't think the full win_config should be a function because then the different configs can't be merged until after they're executed, meaning initialization will be tricky.

**Comment by Bekaboo** [comment]
@willothy Is this ready to merge?

**Comment by willothy** [comment]
I think so, yeah. I've been using my fork with it for a week or so

**Comment by willothy** [comment]
Might be worth making sure it works for you too tho if you haven't tested the latest version :)

**Comment by willothy** [comment]
Agh it behaves differently in the ui-select menu vs the winbar dropdowns. I'll try to finish this up tomorrow.

**Comment by willothy** [comment]
Ok I've fixed the issues I found, I think this is ready for merge. There are still some edge cases, but none that weren't present before afaik. Just things like different borders between fzf and the menu:

- If menu has a border and the fzf window has no border, the fzf window is not wide enough but it is aligned properly.
- If the fzf window has a border but the *menu* doesn't, then the fzf window is too wide, but again aligned properly.

imo those are obscure use cases and can be fixed in followups.

**Comment by willothy** [comment]
Nvm, fixing the widths was pretty trivial so everything seems to be working now.

It does require potentially evaluating the fzf window border twice, but I don't think that's a huge deal.

**Comment by Bekaboo** [comment]
@willothy I have the following error on `fix-fzf-overlap` branch when I press `i` in the ui-select menu:

image

```
E5108: Error executing lua: /home/zeng/Code/dropbar.nvim/lua/dropbar/configs.lua:374: attempt to perfor
m arithmetic on local 'left' (a boolean value)
stack traceback:
        /home/zeng/Code/dropbar.nvim/lua/dropbar/configs.lua:374: in function 'border_width'
        /home/zeng/Code/dropbar.nvim/lua/dropbar/configs.lua:377: in function 'v'
        /home/zeng/Code/dropbar.nvim/lua/dropbar/menu.lua:910: in function 'merge_win_configs'
        /home/zeng/Code/dropbar.nvim/lua/dropbar/menu.lua:956: in function 'fuzzy_find_open'
        /home/zeng/Code/dropbar.nvim/lua/dropbar/configs.lua:278: in function </home/zeng/Code/dropbar.
nvim/lua/dropbar/configs.lua:273>
```

Code snippet used to open the ui-select menu (same as the example in `:h ui.select`):

```lua
vim.ui.select({ "tabs", "spaces" }, {
	prompt = "Select tabs or spaces:",
	format_item = function(item)
		return "I'd like to choose " .. item
	end,
}, function(choice)
	if choice == "spaces" then
		vim.o.expandtab = true
	else
		vim.o.expandtab = false
	end
end)
```

config:

```lua
require('dropbar').setup({
  menu = {
    scrollbar = { background = false },
    win_configs = {
      border = { '', '', '', '' },
    }
  },
})
vim.ui.select = require('dropbar.utils.menu').select
```

**Comment by willothy** [comment]
Hmm interesting, let me check that out.

**Comment by willothy** [comment]
Alright, I think it should work now

**Comment by Bekaboo** [comment]
@willothy fzf window sticking out

image

**Comment by willothy** [comment]
Ahhhh ok just a sec. I think that's specific to ui-select.

**Comment by willothy** [comment]
Ah figured it out. I was confused about how nvim handled 4-char borders.

**Comment by willothy** [comment]
Sorry for the confusion, just lots of edge cases here haha. I *think* it should work now, hopfully I'm not wrong again lol

**Comment by Bekaboo** [comment]
> Sorry for the confusion, just lots of edge cases here haha. I think it should work now, hopfully I'm not wrong again lol

Yeah it's annoying. I think we could simplify the logic by expanding table-valued border whose length is less than 8 to the equivalent border table with 8 elements first then change the borders in different conditions. It can be a utils function in `utils/menu.lua`.

But let's merge this first.

**Pull request merged**
