### PR TITLE
fix: revert 2debe82

### LINKED ISSUE #93: [Bug]: Scrollbar doesn't consistently update
### Description

When moving in the menu, the scrollbar jumps around and sometimes does not move at all.

### nvim version

0.10 nightly

### dropbar.nvim version

b4b6b4a

### Operating system and version

Linux

### Minimal config

```Lua
local tmp = vim.env.TMPDIR
  or vim.env.TEMPDIR
  or vim.env.TMP
  or vim.env.TEMP
  or '/tmp'
local data = tmp ..  '/' .. (vim.env.NVIM_APPNAME or 'nvim')
local packages_root = data .. '/site'
local cloned_root = packages_root .. '/pack/packages/start'
local cloned_path = cloned_root .. '/dropbar.nvim'
local url = 'https://github.com/Bekaboo/dropbar.nvim.git'

vim.fn.mkdir(cloned_root, 'p')
vim.opt.pp:prepend(packages_root)
vim.opt.rtp:prepend(packages_root)

if not vim.loop.fs_stat(cloned_path) then
  vim.fn.system({ 'git', 'clone', url, cloned_path })
end

require('dropbar').setup()
```

### Steps to reproduce

1. Open a menu with a scrollbar
2. Scroll to the bottom of the menu, and back up, one entry at a time.
3. Sometimes the scrollbar will jump to the bottom, sometimes it won't update at all

### Expected behavior

Scrollbar should move when the window / cursor scrolls.

### Actual behavior

Scrollbar jumps around or does not move at all.

### Additional information

Likely caused by 2debe824bc98f6fcdc5ab0d4ec1573f6e5befd15 - tested, reverting that commit fixes the issue.

### PR DESCRIPTION
**Pull request by willothy**
fixes #93

### CODE REVIEW

**Comment by Bekaboo** [comment]
@willothy scrollbar should be updated on WinScrolled now

**Comment by willothy** [comment]
That's not working properly, see #93

**Comment by Bekaboo** [comment]
@willothy Could you send the file `ui.lua` to me? I cannot reproduce the bug on my end.

**Comment by willothy** [comment]
> @willothy Could you send the file `ui.lua` to me? I cannot reproduce the bug on my end.

it's just a huge list of Lazy plugins, I can paste it here if you need but you could recreate the same effect by copy-pasting a bunch of plugin entries.

```lua
return {
  {
      "fake plugin"  -- copy paste this a bunch
  }
}
```

**Comment by Bekaboo** [comment]
So I guess the bug appears when the number of buffer lines exceed some threshold? Could you share how many entries are there in your menu?

**Comment by willothy** [comment]
I don't think that WinScrolled autocmd is executing very often as it's marked Buffer local... it works fine when not buffer local. Happens on menus of all sizes for me, not just large ones.

**Comment by Bekaboo** [comment]
Emm.. Cannot reproduce with 100 menu entries :(


https://github.com/Bekaboo/dropbar.nvim/assets/76579810/7f2fad4a-1f43-4d5c-bd57-3adf06027602

**Comment by willothy** [comment]
Strange, what version of Neovim are you using? I'm on the latest nightly

**Comment by Bekaboo** [comment]
@willothy Nightly but not the latest version

```
NVIM v0.10.0-dev-1181+ge353c869ce
Build type: RelWithDebInfo
LuaJIT 2.1.1694285958
Compilation: /usr/bin/cc -O2 -g -Og -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wvla -Wdouble-promotion -Wmissing-noreturn -Wmissing-format-attribute -Wmissing-prototypes -fno-common -Wno-unused-result -Wimplicit-fallthrough -fdiagnostics-color=auto -fstack-protector-strong -DUNIT_TESTING -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -I/usr/include/luajit-2.1 -I/usr/include -I/build/neovim-git/src/build/src/nvim/auto -I/build/neovim-git/src/build/include -I/build/neovim-git/src/build/cmake.config -I/build/neovim-git/src/neovim-git/src

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"

Run :checkhealth for more info
```

**Comment by willothy** [comment]
Is that before or after [this PR](https://github.com/neovim/neovim/pull/24824)? This PR affected the way topline is restored when setting buf lines, and broke scrolling for some plugins. Testing this now.

**Comment by willothy** [comment]
Is updating on `CursorMoved` a problem? The `update_scrollbar` function isn't especially complex so I doubt there will be any noticeable performance impact.

**Comment by Bekaboo** [comment]
> Is updating on CursorMoved a problem?

Technically not a problem... But you know, we want to  reduce unnecessary calls and make the code clean. I'll test with the lastet nightly version of neovim later.

**Comment by willothy** [comment]
> > Is updating on CursorMoved a problem?
> 
> Technically not a problem... But you know, we want to reduce unnecessary calls and make the code clean. I'll test with the lastet nightly version of neovim later.

For sure, sounds good. I originally tried this same thing when implementing the scrollbar but ran into this issue, that's why I had the call in `CursorMoved` in the first place. If another solution isn't found, maybe it would be good to keep the call in, until there's a cleaner fix? I've tested on a few older 0.10 versions as well and still have the issue, so I'm not sure what's going on.

**Comment by Bekaboo** [comment]
@willothy Still cannot reproduce with minimal config with the latest neovim version:

https://github.com/Bekaboo/dropbar.nvim/assets/76579810/cf2cbff1-c5fd-4d85-98d9-0377ee67db44

Could you try reproducing it using `nvim --clean` instead of using your whole config?

**Comment by willothy** [comment]
Yes, I can reproduce with `nvim --clean` and the minimal init provided, using the `ui.lua` file I showed.

**Pull request merged**
