### PR TITLE
Support background highlight

### LINKED ISSUE #2: [Feature]: Add support for underline
### Problem

Why? 
Underline separates code and top bar nicely. This also prevents to mistaking top bar as part of your code.

[Kitty](https://github.com/kovidgoyal/kitty) terminal has built-in support for this as well neovim.

### Expected behavior

Result should look something like this.
image

This is archived with [lspsaga.nvim](https://github.com/nvimdev/lspsaga.nvim) and with [my custom config](https://github.com/Racle/dotfiles/blob/507fabae6ea6dbc097ffb950ec53f3d1f9b3426c/neovim/.config/nvim/lua/plug-config/lspsaga.lua#L35-L71) to set underline and correct background color to match my "tab" bar (and keep icon colors correct).

### PR DESCRIPTION
**Pull request by theofabilous**
*Originally part of #49*

This PR adds support for a background color on the dropbar. The changes made here are virtually identical to those in #49 (those that pertain to background highlighting), except that the highlight configuration option was removed, and the background color is [instead taken from `hl-WinBar`](https://github.com/Bekaboo/dropbar.nvim/pull/49#discussion_r1255002693). The commits were reorganized for clarity.

Tasks
---

- [x] Remove notes and todo comments
- [x] Run luacheck, stylua, check and pass tests
- [x] Ensure correctness of new `utils.hl.range_single()` which now uses `vim.highlight.range()` instead of `nvim_buf_add_highlight()`. `vim.highlight.range()` is a convenience wrapper for setting extmark highlights, which uses extmark indexing (different from api indexing and mark indexing). See [api-definitions](https://neovim.io/doc/user/api.html#api-definitions) right after the ext types table)
- [x] Add underline support (would close #2)

### CODE REVIEW

**Comment by theofabilous** [comment]
**Note:** Yesterday I added the task to implement underline support, but it looks like it requires more changes than I had anticipated so I think its better left for another PR

**Comment by Bekaboo** [comment]
@theofabilous Thanks, I was thinking adding underline support in this PR but it is also great to implement it in another one.

One of the differences between this two features is that adding underline to the winbar requires retrieving other highlight attributes than `bg`: it would be great if we also support falling back to other attributes defined in `hl-WinBar` or `hl-DropBar`, e.g. if `undercurl=true` in `hl-DropBar`, all highlight groups used in the winbar should have undercurls, this can be done in the setup stage in `hlgroups.lua` instead of generating them in real time like what we do for devicons. I think we can define some new hlgroups, e.g. `_DropBarIconKindConstant` which merges `DropBar` (links to `WinBar` by default) and `DropBarIconKindConstant`, these new hlgroups are not supposed to be modified by users and they exist only for highlight fallback support.

One tricky thing is that we have to support `WinBarNC`, the highlight group used in the winbar for non-current windows. I haven't tested it in your branch if it works. But if we just link `DropBar` to `WinBar` and fallback to attributes defined in it (or directly fallback to `WinBar`), we will have all the winbar having the same background. I can imagine two solutions to this:

1. Adding `DropBarNC` which links to `WinBarNC` by default and use some autocmds to change the winbar color on entering/leaving windows, this is rather complicated and I wonder if it worth the efforts given that most of the users does not set the background colors or other attributes (underline, etc) explicitly for their winbar
2. Just left `DropBar` undefined by default, then nvim will use `WinBar` and `WinBarNC` for regions with no highlight specified automatically. No autocmds required. But if the user customizes the `DropBar` highlight group, `WinBarNC` will not work any more. Not ideal too.

**Comment by theofabilous** [comment]
@Bekaboo

> One of the differences between this two features is that adding underline to the winbar requires retrieving other highlight attributes than `bg`: it would be great if we also support falling back to other attributes defined in `hl-WinBar` or `hl-DropBar`, e.g. if `undercurl=true` in `hl-DropBar`, all highlight groups used in the winbar should have undercurls, this can be done in the setup stage in `hlgroups.lua`

Right, that's basically what I had done in my tentative implementation to support underline. The tricky part about this is that the highlights in the dropbar are the same as those in the menubar, which means that menu entries would also get things like underline, and I think it's safe to assume that this is not the desired behaviour. 

The use of `vim.highlight.range` added in this PR allows stacking highlights via `vim.highlight.priorities` without having to create new highlight groups (only works for buffer highlights tho, not the winbar), so the above issue could be worked around by applying a higher-priority highlight with only `{ nocombine  = true }` to the menu buffer, but then this clears *all* special attributes like bold and italic.

Another method would be to have separate private highlight groups for the winbar and the menu entries. Which brings me to my next point...

**Comment by theofabilous** [comment]
>  I think we can define some new hlgroups, e.g. _DropBarIconKindConstant which merges DropBar (links to WinBar by default) and DropBarIconKindConstant, these new hlgroups are not supposed to be modified by users and they exist only for highlight fallback support.

I think this is a really good idea. I don't know what you had in mind exactly, but if this were to be used, I think it would be necessary to have two private highlight groups for each public highlight group so as to properly address what I mentioned above. E.g.: for `Constant` (`DropBarIconKindConstant`), there could be `_DropBarIconKindConstant_Bar` and `_DropBarIconKindConstant_Menu`, where the first one would be used to highlight in the WinBar (and thus fallback/link to `hl-WinBar`) and the second used for menu entries. But then this necessitates a *lot* of hlgroups. I think it'd be worth to either:
- expose the `DropBarIconKind<kind>` groups as config options instead of defining them as highlight groups, or
- clear them after setup because they'd never actually be used to highlight anything, or
- directly use the public highlight for menu entries and use a private one for highlighting in the WinBar

**Comment by theofabilous** [comment]
> One tricky thing is that we have to support WinBarNC, the highlight group used in the winbar for non-current windows. I haven't tested it in your branch if it works

Yep, good point. It doesn't really work. In terms of solutions, I do think any approach is gonna either not be ideal or require a lot of changes. Correct me if I'm wrong, but the current master doesn't seem to have support for WinBarNC colors. Prior to these changes, having any highlight settings for the WinBar would break highlighting, so as it stands there is no differentiation between dropbars that are current or non-current.

With this in mind, I think for now linking WinBarNC to WinBar (or DropBarNC to WinBar/DropBar) would be fine. Do you agree? I think down the road it'd be worth to support it though

Let me know what you think!

**Comment by Bekaboo** [comment]
@theofabilous Awesome, thanks for your work on this. The implementation is clever and a little tricky, I need some time to go through it before merging it into main.

**Comment by theofabilous** [comment]
@Bekaboo My pleasure! and yes no worries I understand. It still needs some refactoring, but let me know if you have any questions about any of it

**Comment by theofabilous** [comment]
@Bekaboo I think I've fixed the `Expected lua table` error, thanks for catching that, I'll open a PR tomorrow.

Not sure what you mean by
> found that dropbar.nvim no longer launch itself automatically in this branch, could you fix it?

Could you please clarify? If you mean that dropbar doesn't load without an explicit call to `setup(...)` then I can't reproduce this. What package manager are you using?

**Comment by Bekaboo** [comment]
@theofabilous 

> If you mean that dropbar doesn't load without an explicit call to setup(...) 

Yes that is what I mean. After using a minimal config the problem is gone, so I think it is probably some issues in my testing config.

> I think I've fixed the Expected lua table error, thanks for catching that, I'll open a PR tomorrow.

Thanks and looking forward for the fix!

**Comment by Bekaboo** [comment]
@theofabilous There are still some bug around in this branch that I'm trying to fix:

1. The background of the menu does not follow `DropBarMenuNormalFloat`
2. The foreground of the text part of each symbol in non-current winbar does not follow `WinBarNC`
3. Cannot set custom color for symbol icons

In addiction, the current implementation does not allow user to change some highlight groups without triggering event `Colorscheme`.

Current implementation still seems fragile and unnecessarily complex, including hacks like ignoring certain hlgroups and dropping certain attributes when setting highlights, which might increase the difficulty of future maintenance. In `master` branch, if the user wants background color, they can override highlight groups of symbols returned from the sources, like what is discussed in #2. Comparing the changes made in this branch to the solution in #2, I have a feeling that too much work have to be done for few improvements.

From now on I'll mainly work on merging some "safe" changes from this branch, e.g. improvements for the utils functions, etc and start to review and merge branches `feat-fuzzy-finding` and `feat-sources`. Thanks for your work for bug fixes and improvements on highlighting issues!

**Comment by serhez** [comment]
Hello! Is this going to be merged? Thanks :)

**Comment by willothy** [comment]
> Hello! Is this going to be merged? Thanks :)

Not sure of the current state since this branch is pretty far behind the main branch, but from the above comments it seems like there's still some work to do here before the PR is ready. #2 has a solution that should work on the main branch, though I haven't tested it myself.

@Bekaboo maybe it would be good to update the `feat-winbar-background-highlight` to the latest dropbar version though, so that people can give this feature a try.

**Pull request merged**
