### PR TITLE
feat: add builtin source for terminal buffers

### PR DESCRIPTION
**Pull request by willothy**
Allows using the dropdown menu to quickly switch between terminal buffers. Wrote this for my own config but figured I'd share since it's been useful.

All menu properties can be set to either strings or functions in the config, so it can be integrated easily with any terminal-related plugin. I have mine setup to use toggleterm. It will also work with default nvim terminal buffers.

### CODE REVIEW

**Comment by Bekaboo** [comment]
@willothy Thanks, just tested it and it works smoothly. Could you include the changed of the default config in readme and vimdoc and label this as a breaking change? Also we need to explain how to customize the new `terminal` source, e.g. how to change the name/color/icon of terminal appearing in the winbar, corresponding hlgroups, etc. Lastly it would be nice to include the current terminal itself in the drop-down menu to better align with the behavior of other sources.

**Comment by willothy** [comment]
> @willothy Thanks, just tested it and it works smoothly. Could you include the changed of the default config in readme and vimdoc and label this as a breaking change? 

Definitely, will update the docs. Glad it's working well!

> Also we need to explain how to customize the new `terminal` source, e.g. how to change the name/color/icon of terminal appearing in the winbar, corresponding hlgroups, etc. 

I can provide an example from my config in the docs, if that works?

> Lastly it would be nice to include the current terminal itself in the drop-down menu to better align with the behavior of other sources.

This actually is already an option, I'll make it the default setting though.

**Comment by Bekaboo** [comment]
> >    Also we need to explain how to customize the new terminal source, e.g. how to change the name/color/icon of terminal appearing in the winbar, corresponding hlgroups, etc.
>
> I can provide an example from my config in the docs, if that works?

No, I mean explaining each option that `terminal` source accepts in [README sources section](https://github.com/Bekaboo/dropbar.nvim#sources) and also update the [full config table](https://github.com/Bekaboo/dropbar.nvim#options), you might also want to update the hlgroups and icons used, there is a [separate section](https://github.com/Bekaboo/dropbar.nvim#highlighting) listing all highlight groups used by dropbar. Notice that these updates also applies to the vimdoc help file.

**Comment by willothy** [comment]
> No, I mean explaining each option that `terminal` source accepts in [README sources section](https://github.com/Bekaboo/dropbar.nvim#sources) and also update the [full config table](https://github.com/Bekaboo/dropbar.nvim#options), you might also want to update the hlgroups and icons used, there is a [separate section](https://github.com/Bekaboo/dropbar.nvim#highlighting) listing all highlight groups used by dropbar. Notice that these updates also applies to the vimdoc help file.

Oh, yes, definitely was going to do that, I meant in addition to that to show an example of integration with another plugin (toggleterm). 

Will update the hlgroups as well.

**Comment by Bekaboo** [comment]
> I meant in addition to that to show an example of integration with another plugin (toggleterm).

That will be really nice, looking forward for the update!

**Comment by willothy** [comment]
Working on it right now, though it's late here so might end up finishing the changes tomorrow.

**Comment by Bekaboo** [comment]
@willothy Take your time, we are not in a hurry :)

**Comment by willothy** [comment]
Alright, I think the current setup of hlgroups works well. Is there a different icon that would be preferable?

**Comment by willothy** [comment]
I think that's everything, let me know what you think!

**Comment by Bekaboo** [comment]
@willothy Looks great! Could you move the icon customization under `opts.icons.kinds` and use a fixed hlgroup name? IMO allowing user to change the actual hlgroup used directly could easily cause confusion and increase the work of colorscheme authors, could we use a fixed highlight group for icons/names of terminal buffers in the winbar? Users can still customize the colors using `vim.api.nvim_set_hl()`. You can check [lua/hlgroups.lua](https://github.com/Bekaboo/dropbar.nvim/tree/master/lua/dropbar/hlgroups.lua) for refrence and define the default highlight groups there -- my suggestion is leaving the text highlight group undefined so that they follow `hl-WinBar` or `hl-WinBarNC` and only define the icon colors.

**Comment by willothy** [comment]
> @willothy Looks great! Could you move the icon customization under `opts.icons.kinds` 

I actually think the icon customization for the terminal should stay where it is, because the API for it differs from the regular kind icons as it can accept a function for per-terminal dynamic icons. The reason for this is that people may want to show different icons depending on things like the process running in the terminal, like using the git devicon for a lazygit terminal, etc..

> IMO allowing user to change the actual hlgroup used directly could easily cause confusion and increase the work of colorscheme authors, could we use a fixed highlight group for icons/names of terminal buffers in the winbar? 

That makes sense, will do. Is it reasonable to create a new group such as `DropBarIconKindTerminal`?

**Comment by willothy** [comment]
Moved the highlight groups, but I left the icon customization where it is for now as I think it would be confusing to have that in the same place as the kind icons.

**Pull request merged**
