### PR TITLE
feat: fuzzy finding (pt. 2)

### PR DESCRIPTION
**Pull request by willothy**
This PR builds on @theofabilous' great work in #65, adding mouse hover support, proper offset for borderless finder prompts, and config options for the fuzzy finder.

- [x] Hover events
- [x] Config options
- [x] Docs for config options
- [x] Docs for API 
- [x] Properly restore cursor in menu when exiting fuzzy finding mode
- [x] Default mapping to open fuzzy finder from menu (needs discussion)
  - Set to <kbd>i</kbd> for now
- [x] Tests for fuzzy finder

### CODE REVIEW

**Comment by willothy** [comment]
Anything need changing before I start writing tests? I've been using this and it's working quite well :)

**Comment by Bekaboo** [comment]
@willothy Thanks for your work, at a glance this looks polished and well-organized. I'm quite busy these days and will review and merge this in a week hopefully.

**Comment by willothy** [comment]
> @willothy Thanks for your work, at a glance this looks polished and well-organized. I'm quite busy these days and will review and merge this in a week hopefully.

Thanks, that sounds good! That will give me some time to keep testing and fix any issues that pop up.

**Comment by willothy** [comment]
Todo: current context is not highlighted in fzf mode

**Comment by willothy** [comment]
This is working very smoothly for me now, no issues that I know of.

**Comment by willothy** [comment]
Fixed error when fzf-native isn't installed, now attempting to enter fzf mode without fzf-native will do nothing.

**Comment by willothy** [comment]
I'll squash these small commits before merge, but figured I should leave them separate before review

**Comment by willothy** [comment]
Tests and CI done

**Comment by willothy** [comment]
What is your preference for squashing these commits? Should I combine all of them into one?

**Comment by Bekaboo** [comment]
@willothy It is fine leaving them as seperate commits

**Comment by willothy** [comment]
Will update this and add scrollbar compatibility tomorrow!

**Comment by willothy** [comment]
Updated! CI failure is related to swap files, not the PR contents btw

**Pull request merged**
