### PR TITLE
feat: support preview for entries in path source menus

### PR DESCRIPTION
**Pull request by willothy**
Adds support for previewing files from the path source.

### CODE REVIEW

**Comment by willothy** [comment]
Considering an alternate approach here... what if the previews for files worked the same way as for TS/LSP sources, where the file is previewed in the active window instead of a popup? I think that would allow the preview to be more consistently visible, since having nested menus open significantly shrinks the space available for the preview popup.

**Comment by willothy** [comment]
Not quite ready for merge but ready to be tested - now supports previewing in a floating window, or in the current window like document symbols are previewed.

**Comment by willothy** [comment]
Ok fixed the bugs, this should be pretty much ready as well.

**Comment by willothy** [comment]
@Bekaboo  this has been working well in my config for a bit, I'll upload a new video here today.

Do we want to have the floating preview though? It's different from how all of the other previews work and I'm not sure I'm a fan of it - I kinda want to remove it and have this PR only support preview in the way we already do in order to keep things consistent between the sources. Thoughts?

**Comment by Bekaboo** [comment]
@willothy Thanks for your work!

> Do we want to have the floating preview though? It's different from how all of the other previews work and I'm not sure I'm a fan of it - I kinda want to remove it and have this PR only support preview in the way we already do in order to keep things consistent between the sources. Thoughts?

I agree with you.

**Comment by willothy** [comment]
Cool, sounds good! I'll clean this up and remove the floating preview.

**Comment by Bekaboo** [comment]
@willothy Is this ready to merge?

**Comment by willothy** [comment]
Uhh I forget, I'll look over it today and let you know. I think I just need to do a little bit of cleanup.

**Comment by willothy** [comment]
@Bekaboo ok, good to go! Sorry for the delay.

**Comment by Bekaboo** [comment]
Ty, looks great! @willothy I have been a bit busy recently but I'll review and merge this ASAP.

**Comment by willothy** [comment]
Sounds good! No rush :)

**Comment by Bekaboo** [comment]
@willothy Why do we need a new field `preview_win`? Before this patch, we always preview symbols in the current window (the window that the dropbar is attached to) and the window id is stored in `dropbar_symbol_t.win`, i.e. it is the symbol instead of the menu that is responsible for previewing.

**Comment by willothy** [comment]
Right, good catch! That's leftover from the popup preview, I should've removed it. I'll get rid of that now :)

**Comment by willothy** [comment]
@Bekaboo I've rebased onto master and removed the `preview_win` field. Should be all good now.

**Comment by Bekaboo** [comment]
@willothy Merged, thank you for your contribution!

**Pull request merged**
